# Generated by Django 4.2.1 on 2023-05-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_rename_parent_user_classroom_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='parent_pp',
        ),
    ]
