# Generated by Django 4.2.1 on 2023-05-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0005_alter_classroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(null=True),
        ),
    ]
