# Generated by Django 4.2.1 on 2023-05-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0006_remove_studentprofile_avatar_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_photos'),
        ),
    ]
