# Generated by Django 4.2.1 on 2023-05-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0011_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='img/course_images'),
        ),
    ]
