# Generated by Django 4.2.1 on 2023-05-18 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0013_alter_parentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
